apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-web
  namespace: academy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-web
  template:
    metadata:
      labels:
        app: academy-web
    spec:
      serviceAccountName: academy-app
      containers:
        - name: web
          image: nginx:1.27-alpine
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_DB
              value: "academy"
            - name: POSTGRES_USER
              value: "academy_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: academy-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "127.0.0.1"
            - name: POSTGRES_PORT
              value: "5432"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          args:
            - "--port=5432"
            - "ls-platform-gitops:us-east1:academy-postgres"
          securityContext:
            runAsNonRoot: true
