apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: academy-db-secret
  namespace: academy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: academy-db-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: academy-db-password
  dataFrom: []
