apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: academy-web
  namespace: academy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - academy.lstractorusa.com
      secretName: academy-tls
  rules:
    - host: academy.lstractorusa.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: academy-web
                port:
                  number: 80
